package lk.ijse.phone.util;

public enum Routes {
    AVA,MAINFORM,PENDINGORDERS,PACKEDORDERS,SALESBILLING,RETURNITEM,ORDERS,PAYMENT,ADDCUSTOMERS,ADDSTOCK,SUPPLIYER,EMPLOYEE,
    SEARCHSTOCK,STOCKPLACE,STOCKARRIEVD,CREATESYSTEMUSERS,LOGIN,SHOWSTOCK,HR,ADDPLACES,ADDSTOCKARRIEVD,INCOMEREPORT
    ,SHOWORDERDETAILS,MAINFORMEMPLOYEE,ADDSYSTEMUSERS
}
